version: '3.8'

services:
  customer-data-service:
    build:
      context: ./CustomerDataService  # Set the CustomerDataService directory as the build context
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - GO_ENV=production
    networks:
      - go-api-network

  documents-service:
    build:
      context: ./DocumentsService  # Set the DocumentsService directory as the build context
      dockerfile: Dockerfile
    ports:
      - "7000:7000"  # Ensure proper port mapping
    environment:
      - GO_ENV=production
    networks:
      - go-api-network

networks:
  go-api-network:
    driver: bridge
