version: '3.8'

services:
  go-app:
    build:
      context: ./  # Set the root of your project as the context
      dockerfile: ./Dockerfile  # Dockerfile inside the app folder
    ports:
      - "8000:8000"
    environment:
      - GO_ENV=production
    # Mount the source code (ensure no overwrite issues)
    networks:
      - go-api-network

networks:
  go-api-network:
    driver: bridge
